# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-cjozdt8w.sql.tencentcdb.com:21670/gulimall-pms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: CNTweiai1314
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: gulimall-product
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000
logging:
  level:
    com.ccc.gulimall: debug

