alibaba:
  cloud:
    access-key: LTAI5tKPNG68Phc9dRT7eZd2
    secret-key: eqmT7txMO4ivBsCWJw00UB1a9e1QG4
    bucket: gulimall-cntt
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com  #地域节点

spring:
  application:
    name: gulimall-third-party

  cloud:
    nacos:
      server-addr: localhost:8848
server:
  port: 30000